### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by LatinP** [FlameNET/FlameCMS#4]
When I try to install the cms I click the install now button and I immediately get pushed to a 404 page at step 2.

Using IIS 8.0 on Windows Server 2012 r2, usually I have no problem with rewrite rules but this one has me scratching my head.

 Also you have serveral:
Warning: Cannot modify header information - headers already sent by (output started at ROOT\wowserver\index.php:2)

You may need to check files for white spaces.

**Comment by oneluiz** [comment]
Many PHP applications are distributed with configuration files for the Apache Web server. These configuration files (usually called .htaccess files) and you have to convert the .htaccess content for IIS web.config , see this link: [SAMPLE APPLICATION .HTACCESS FILE](http://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig)
OR
try entering the following link:  http://YOUR-DOMAIN/install/step-3.php
you have to put the file extension "php"

**Comment by LatinP** [comment]
Ok so today I installed apache/php/mysql on my local machine to test this even with rewrite rules it still sends me to a 404 page. If I type .php at the end it works but every single step including the sucess page will turn a 404. I've also installed countless other scripts with mod rewrite on and never had a problem, is there anything else I want to add in the htaccess file to make this work properly?

**Comment by oneluiz** [comment]
you use? xampp, wamp or you installed the packages separately?? you enable mod_rewrite???

**Comment by Addra** [comment]
Please deliver .htaccess file

**Comment by Thelodin** [comment]
be sure , you enabled these functions in your apache website config, otherwise php is forbidden to add the .php extension to the URL:
somewhere between 
< VirtualHost yourDomain:80>
....... and ....
< /VirtualHost>
add these line:

```
    AcceptPathInfo On
```

in your apache2.conf (linux) or httpd.conf (win/xampp), add ord edit these lines
between your < Directory websitepath> and < /Directory> :

```
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
```

AND on Win/xampp delete the # in front of this line:

```
  LoadModule rewrite_module modules/mod_rewrite.so
```

for Linux just link the file rewrite.load vom the mods-available to the mods-enable directory
Now restart your Apache and all should be fine.

regards, thelo

p.s.: for you Haras aka Addra: a .htaccess file is included ;) Schönen Tag noch

**Comment by Addra** [comment]
rewrite the .htaccess-file please for nginx too. NXING becomes popular

Thank you

**Comment by oneluiz** [comment]
## \* IIS 8.0:

http://www.iis.net/downloads/microsoft/url-rewrite

## \* NGINX:

http://winginx.com/en/htaccess

example

```
# nginx configuration
error_page 404 http://localhost/404;
location / {
if (!-e $request_filename){
rewrite ^(.*)$ /$1.php break;
}
}
location /blog {
rewrite ^/blog/(.+)/(.+)$ /article.php?id=$1&title=$2;
}
```

commits: bdfc78bf323151725e5a9f4b92de451e9d5c0471
